"""added trainer profile as a one to one with user

Revision ID: 1d28f5a29afd
Revises: 3ee05c4a8172
Create Date: 2022-08-15 12:21:16.529850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d28f5a29afd'
down_revision = '3ee05c4a8172'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainer_profile',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=24), nullable=True),
    sa.Column('last_name', sa.String(length=24), nullable=True),
    sa.Column('company_name', sa.String(length=64), nullable=True),
    sa.Column('phone_number', sa.String(length=10), nullable=True),
    sa.Column('website', sa.String(length=64), nullable=True),
    sa.Column('branding_image', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trainer_profile_company_name'), 'trainer_profile', ['company_name'], unique=False)
    op.create_index(op.f('ix_trainer_profile_last_name'), 'trainer_profile', ['last_name'], unique=False)
    op.create_index(op.f('ix_trainer_profile_website'), 'trainer_profile', ['website'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trainer_profile_website'), table_name='trainer_profile')
    op.drop_index(op.f('ix_trainer_profile_last_name'), table_name='trainer_profile')
    op.drop_index(op.f('ix_trainer_profile_company_name'), table_name='trainer_profile')
    op.drop_table('trainer_profile')
    # ### end Alembic commands ###
