"""added customer profile model tied to user model

Revision ID: 26dbab86ca43
Revises: 51d2a90f0d29
Create Date: 2022-08-15 16:05:16.368447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26dbab86ca43'
down_revision = '51d2a90f0d29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=24), nullable=True),
    sa.Column('last_name', sa.String(length=24), nullable=True),
    sa.Column('phone_number', sa.String(length=10), nullable=True),
    sa.Column('branding_image', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_user_email', table_name='user')
    op.drop_column('user', 'email')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'company_name')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.VARCHAR(length=32), nullable=True))
    op.add_column('user', sa.Column('phone', sa.VARCHAR(length=120), nullable=True))
    op.add_column('user', sa.Column('company_name', sa.VARCHAR(length=140), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.VARCHAR(length=32), nullable=True))
    op.add_column('user', sa.Column('email', sa.VARCHAR(length=120), nullable=True))
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    op.drop_table('customer_profile')
    # ### end Alembic commands ###
