"""removed additional indexes

Revision ID: 3684a9b20b20
Revises: 1d28f5a29afd
Create Date: 2022-08-15 13:24:46.089859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3684a9b20b20'
down_revision = '1d28f5a29afd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trainer_profile_company_name', table_name='trainer_profile')
    op.drop_index('ix_trainer_profile_last_name', table_name='trainer_profile')
    op.drop_index('ix_trainer_profile_website', table_name='trainer_profile')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_trainer_profile_website', 'trainer_profile', ['website'], unique=False)
    op.create_index('ix_trainer_profile_last_name', 'trainer_profile', ['last_name'], unique=False)
    op.create_index('ix_trainer_profile_company_name', 'trainer_profile', ['company_name'], unique=False)
    # ### end Alembic commands ###
