"""Added additional user info to users and posts table to start on ticketing system

Revision ID: 3ee05c4a8172
Revises: 834b1a697901
Create Date: 2022-08-09 17:26:57.341504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ee05c4a8172'
down_revision = '834b1a697901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('title', sa.String(length=160), nullable=True))
    op.add_column('post', sa.Column('reference_link', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('first_name', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('phone', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('company_name', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'company_name')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'is_admin')
    op.drop_column('post', 'reference_link')
    op.drop_column('post', 'title')
    # ### end Alembic commands ###
