"""fixed relationship between trainer_profile and the billing and meal_plans

Revision ID: 447cf3e38a75
Revises: a6e049d4e6a4
Create Date: 2022-08-19 16:16:17.629902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '447cf3e38a75'
down_revision = 'a6e049d4e6a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal_plan', sa.Column('free_plan', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meal_plan', 'free_plan')
    # ### end Alembic commands ###
