"""added CustomerSubscription model

Revision ID: 829f02f74de2
Revises: 1a4d5825933a
Create Date: 2022-08-16 19:22:22.546633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '829f02f74de2'
down_revision = '1a4d5825933a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('billing_id', sa.Integer(), nullable=True),
    sa.Column('trainer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['billing_id'], ['billing_plan.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['customer_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_subscription')
    # ### end Alembic commands ###
