"""moved profile info out of the user table and into a profile table

Revision ID: cee6b6b0e70e
Revises: 3684a9b20b20
Create Date: 2022-08-15 15:02:04.645319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cee6b6b0e70e'
down_revision = '3684a9b20b20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_email', table_name='user')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'email')
    op.drop_column('user', 'company_name')
    op.drop_column('user', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone', sa.VARCHAR(length=120), nullable=True))
    op.add_column('user', sa.Column('company_name', sa.VARCHAR(length=140), nullable=True))
    op.add_column('user', sa.Column('email', sa.VARCHAR(length=120), nullable=True))
    op.add_column('user', sa.Column('first_name', sa.VARCHAR(length=32), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.VARCHAR(length=32), nullable=True))
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    # ### end Alembic commands ###
